name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]
    tags:   [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.anenna }}
        password: ${{ secrets.dckr_pat_CG53hYKvjHpV-1YF0I5qOqygZDM }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          b1r0c/tvproxy:latest
          b1r0c/tvproxy:${{ github.ref_name }}
